# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

new_func_sd <- function(X) {
    .Call(`_isodisregSD_new_func_sd`, X)
}

new_func_eps <- function(X) {
    .Call(`_isodisregSD_new_func_eps`, X)
}

normal_comp_eps <- function(X) {
    .Call(`_isodisregSD_normal_comp_eps`, X)
}

normal_comp_sd <- function(X) {
    .Call(`_isodisregSD_normal_comp_sd`, X)
}

normal_comp_sd_ab <- function(X, a, b) {
    .Call(`_isodisregSD_normal_comp_sd_ab`, X, a, b)
}

indx_norm_sd <- function(X, x) {
    .Call(`_isodisregSD_indx_norm_sd`, X, x)
}

new_func2_sd <- function(X, x) {
    .Call(`_isodisregSD_new_func2_sd`, X, x)
}

new_func_single_grid_sd <- function(X, x, vec) {
    .Call(`_isodisregSD_new_func_single_grid_sd`, X, x, vec)
}

new_func_mat_sd <- function(X, x, gridx, gridX) {
    .Call(`_isodisregSD_new_func_mat_sd`, X, x, gridx, gridX)
}

new_func_mat_list_sd <- function(X, x, gridx, gridX) {
    .Call(`_isodisregSD_new_func_mat_list_sd`, X, x, gridx, gridX)
}

new_func_list_sd_back <- function(X, x, gridx, gridX) {
    .Call(`_isodisregSD_new_func_list_sd_back`, X, x, gridx, gridX)
}

new_func_list_sd <- function(X, x, gridx, gridX) {
    .Call(`_isodisregSD_new_func_list_sd`, X, x, gridx, gridX)
}

new_func_list_mat_sd <- function(X, x, gridx, gridX) {
    .Call(`_isodisregSD_new_func_list_mat_sd`, X, x, gridx, gridX)
}

ecdf_list_comp_class_sd <- function(X, t) {
    .Call(`_isodisregSD_ecdf_list_comp_class_sd`, X, t)
}

ecdf_list_comp_class_eps <- function(X, t) {
    .Call(`_isodisregSD_ecdf_list_comp_class_eps`, X, t)
}

ecdf_comp_sd <- function(X, t) {
    .Call(`_isodisregSD_ecdf_comp_sd`, X, t)
}

ecdf_comp_eps <- function(X, t) {
    .Call(`_isodisregSD_ecdf_comp_eps`, X, t)
}

ecdf_comp_class_sd <- function(X, t) {
    .Call(`_isodisregSD_ecdf_comp_class_sd`, X, t)
}

ecdf_func <- function(X, t, thresholds) {
    .Call(`_isodisregSD_ecdf_func`, X, t, thresholds)
}

ecdf_func_mat <- function(X, t, thresholds) {
    .Call(`_isodisregSD_ecdf_func_mat`, X, t, thresholds)
}

ecdf_comp_class_ind <- function(X) {
    .Call(`_isodisregSD_ecdf_comp_class_ind`, X)
}

ecdf_list_comp_class_ind <- function(X, t) {
    .Call(`_isodisregSD_ecdf_list_comp_class_ind`, X, t)
}

ecdf_comp_class_eps <- function(X, t) {
    .Call(`_isodisregSD_ecdf_comp_class_eps`, X, t)
}

pavaCorrect <- function(y) {
    .Call(`_isodisregSD_pavaCorrect`, y)
}

